### PR TITLE
Update message.json of zh_CN

### PR DESCRIPTION
**Pull request by NightSharp**
Complete and correct the translation for zh_CN

### CODE REVIEW

**Comment by piroor** [comment]
Sorry for long delay, thanks a lot!

**Comment by NightSharp** [comment]
> Sorry for long delay, thanks a lot!

Hi there, I updated the TST's translation on GitLocalize, showing 99% Translated, same as your English template.
Would you mind merging that in TST ?

**Comment by piroor** [comment]
Thanks! Could you create a new review request from https://gitlocalize.com/repo/6376/zh_CN/webextensions/_locales/en/messages.json , submit it and create a new PR from changes?

**Comment by NightSharp** [comment]
> Thanks! Could you create a new review request from https://gitlocalize.com/repo/6376/zh_CN/webextensions/_locales/en/messages.json , submit it and create a new PR from changes?

Done

**Pull request merged**
