### PR TITLE
Create ru

### PR DESCRIPTION
**Pull request by wvxwxvw**
I couldn't see the translation. When replacing other languages, it is not picked up by the extension. Make a TEST version, I'll check.

### CODE REVIEW

**Comment by scorpie67** [comment]
Had to install russian, but works as a temporary addon

ru

even with one that I signed for me it works without errors/warnings

**Comment by wvxwxvw** [comment]
**scorpie67** 
Strange. Attach your version of the add-on.

**Comment by scorpie67** [comment]
[tst_bookmarks_subpanel-1.0.0.31ru-fx.zip](https://github.com/piroor/tst-bookmarks-subpanel/files/3815843/tst_bookmarks_subpanel-1.0.0.31ru-fx.zip)
 rename to xpi

**Comment by wvxwxvw** [comment]
**scorpie67**
Got it. I tried to replace the language rather than add. Previously, in other extensions (perhaps up to quantum), I was able only in this way. Thank you.

**Comment by wvxwxvw** [comment]
I'm removing it to create a new one.

**Comment by wvxwxvw** [comment]
I'm removing it to create a new one.

**Pull request closed without merging**
